name: PlatformIO CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths:
      - "examples/**"
      - ".github/workflows/esp-idf.yml"

jobs:
  build:
    runs-on: ubuntu-latest  # 指定的运行器环境中运行 [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        idf_ver: ["latest"]

        example: 
          - examples/nvs_rw_blob
          - examples/i2c_tools
          - examples/mipi_dsi_lvgl9

    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build esp-idf examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          cd ${{ matrix.example }}
          idf.py build

